resources:
- name: 'x'
  type: time
  source:
    interval: 20s
  check_every: 20s
- name: 'y'
  type: time
  source:
    interval: 2000h
jobs:
- name: +
  serial: true
  plan:
  - get: 'x'
    trigger: true
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: false
- name: +=+=+=
  serial: true
  plan:
  - get: 'x'
    trigger: true
  - get: 'y'
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: sleep
        args: [19]
- name: =+=+=+=+=+=
  serial: true
  plan:
  - get: 'x'
    trigger: true
  - get: 'y'
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: sleep
        args: [10]
- name: +=+=+=+=+=+=+=+=+
  serial: true
  plan:
  - get: 'x'
    trigger: true
  - get: 'y'
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: sleep
        args: [19]
- name: =+=+=+=+=+=+=+=+=+=+=+
  serial: true
  plan:
  - get: 'x'
    trigger: true
  - get: 'y'
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: sleep
        args: [10]
- name: +=+=+=+=+=+=+=+=+=+=+=+=+=+=
  serial: true
  plan:
  - get: 'x'
    trigger: true
  - get: 'y'
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: sleep
        args: [19]
- name: =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
  serial: true
  plan:
  - get: 'x'
    trigger: true
  - get: 'y'
    trigger: true
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: sleep
        args: [10]
- name: +++
  serial: true
  plan:
  - get: 'y'
    trigger: true
  - task: shine
    config:
      platform: linux
      image: "docker:///alpine"
      run:
        path: sleep
        args: [59]
